<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Arbitarr.Ai</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arbitarr.Core\Arbitarr.Core.csproj" />
  </ItemGroup>

</Project>
