<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Arbitarr.Media</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arbitarr.Core\Arbitarr.Core.csproj" />
    <ProjectReference Include="..\Arbitarr.Core.Identity\Arbitarr.Core.Identity.csproj" />
    <ProjectReference Include="..\Arbitarr.Data\Arbitarr.Data.csproj" />
  </ItemGroup>

</Project>
